name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PIP_CACHE_DIR: ~/.cache/pip

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8] #, 3.9]
        # FIXME: Wheels for mayavi and VTK are not available for Python 3.9 yet

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip requirements
      id: pip-cache
      uses: actions/cache@v2
      with:
        path: ${{ env.PIP_CACHE_DIR }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.*') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Verify Python environment
      run: |
        pip list
        pip cache list

    - name: Install dependencies
      run: |
        pip install -e .[tests]

    - name: Run tests
      run: pytest -s -v -n 4

    - name: Upload coverage
      if: ${{ success() && matrix.python-version == '3.7' }}
      run: |
        pip install coveralls
        coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
